import type { Metadata } from "next";
import "@uploadthing/react/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Toaster} from "sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en" className="h-full">
  <body className={`relative h-full antialiased min-h-screen ${inter.className}`}>
    <main className="relative flex flex-col min-h-screen bg-background">
      <Navbar />
      <div className="flex-grow flex-1">
        {children}
      </div>
    </main>

    <Toaster richColors position="top-center"/>
  </body>
</html>
  );
}
